### ISSUE TITLE
jQuery issues

### ISSUE THREAD

**Issue by ghost** [mindmup/editable-table#23]
I am trying to use this plugin for my project, but I have saw an issue that I don't use $ is jQuery method call, by default I use jQuery() to solve some javascript libraries conflict. May you use (function($) {...}(jQuery)).

**Comment by franciscod** [comment]
This is prbbably not a editabletable's issue. Would you detail what is your problem and specially the 'libraries conflict' part? Maybe this is your solution: https://api.jquery.com/jquery.noconflict/

**Comment by jadware** [comment]
Very common issue with some distributions of jquery, and unrelated to editable-table.
Add this to one of your scripts somewhere:
`var $ = jQuery;`
